### ISSUE TITLE
line 109 mine head hurthed

### ISSUE THREAD

**Issue by Xenopos** [Xenopos/Death-Minuet#2]
if (gameState.Xiyactions[choosingAction].actioninput < 1 || gameState.Xiyactions[choosingAction].actioninput > 4) {
                hasInvalidactioninput = 1;
                printf("Invalid action input. Please enter numbers between 1 and 4 or 0 to clear.\n");
                clear_input_buffer();
                continue;
            }

**Comment by Ky-ro** [comment]
if (choosingAction >= 0 && choosingAction < sizeof(gameState.Xiyactions) / sizeof(gameState.Xiyactions[0])) {
    int actionInput = gameState.Xiyactions[choosingAction].actioninput;
    if ((actionInput < 1 || actionInput > 4) && actionInput != 0) {
        hasInvalidactioninput = 1;
        printf("Invalid action input. Please enter numbers between 1 and 4 or 0 to clear.\n");
        clear_input_buffer();
    } else {
        hasInvalidactioninput = 0;
    }
} else {
    printf("Error: choosingAction index out of bounds.\n");
}



???

**Comment by Xenopos** [comment]
fuck you it is resolve
